[Logger]
# максимальное количество сообщений в памяти до сброса в файл
mmax=100
# максимальный размер одного файла в байтах
fsize=1000000
# путь к файлу. Если не задан, то будет лежать рядом с исполняемым файлом
fpath=
# количество файлов в ротации
fnum=3
# уровень логирования (ERROR, WARN, INFO, DEBUG, SPEC)
level=WARN
# ориентировочное время простоя потока логирования (регулируется автоматически), мс
stime=10000

[Params]
# адрес конвертера. В нашем случае, подключен к этому порту USB
destination=/dev/ttyUSB0
#type=1 MODBUS_USB
#type=2 MODBUS_TCP
# у нас конвертер подключен к USB, тип 1
type=1
# интервал опроса устройств в мс. По факту - не работает, так как чтение идет медленно
poll=100  
# таймер отправки данных в OpenHAB, миллисекунд
report=3000
# url item'а вашего OpenHAB, который будет получать строку со всеми измеренными параметрами
rep_url=your_openhab_ip:8080/rest/items/Your_Item
# токен для доступа к вашему OpenHAB
bearer=your_token
# таймаут отправки в OpenHAB, миллисекунды
timeout_ms=700

# Адреса и типы опрашиваемых по Modbus устройств. Адрес-Тип

[Addresses]
5=PZEM016
10=PZEM016
15=MBSL8AI

# параметры калибровки показаний аналоговых датчиков, подключенных к 8-канальному ридеру по адресу 15.

[15]
AI1_offset=819
AI1_max=93.6
AI2_offset=824
AI2_max=95
AI3_offset=819
AI3_max=0
AI4_offset=819
AI4_max=45.0
AI5_offset=825
AI5_max=99
AI6_offset=782
AI6_max=48.6
AI7_offset=819
AI7_max=0
AI8_offset=819
AI8_max=0

